### PR TITLE
Publication image sizes

### PR DESCRIPTION
**Pull request by sgulseth**
Allow each publication to define their own image sizes. https://github.com/aptoma/drpublish-imbo-app/issues/1

When resizing images use img-selector instead img[data-transformations]

Also added cachebreaking of javascript.

### CODE REVIEW

**Comment by mipli** [comment]
Should the `buildRenditions` function in `ImageEditor` also output the new image sizes? At the moment it only outputs three hardcoded sizes.

**Comment by sgulseth** [comment]
What is the use case for buildRenditions? Can't see it being used?

**Comment by mipli** [comment]
The PHP Client can use them for resizing the image if you take a look at the code here: https://github.com/aptoma/drpublish-api-client-php/blob/imbo-integration/lib/core/content/DrPublishApiClientArticleImageElement.php#L74

**Comment by sgulseth** [comment]
All right. but how does the articles manage the renditions? Lets say i create an article with default- and small-size defined in renditions, and a while later i add a new rendition called "medium". Will the old articles have medium rendition defined then? I'm wondering since it looks like renditions are coming from drlib

**Comment by mipli** [comment]
That's correct. The renditions are stored in DrLib when saving the article, so if you make changes to the renditions afterwards they would not be available for the given image.

**Comment by sgulseth** [comment]
Ok! We most likely wont use this feature, but I commited a fix for it.

**Comment by mipli** [comment]
Looks good, but I think we should require the `highRes` version of the image to always be present. So users of the API know what name to require when they want a full size version of the image. 

Today that name is also used by NewsPilot when importing articles from us, so it's important that all articles that they get have that image size.

**Comment by sgulseth** [comment]
All right. Is there any other sizes which always should be present in buildRenditions? and how large is highRes?

**Comment by mipli** [comment]
I think `highRes` is the only size which is required. 

`highRes` is an untouched image, so it should be as big as the original file is.

**Comment by sgulseth** [comment]
Ok, now it will return the original image as with "highRes"-key in renditions

**Pull request merged**
